

providers:
  llm:
    provider: groq                 
    model: llama-3.1-70b-versatile
    temperature: 0.0
  embeddings:
    provider: huggingface          
    model: BAAI/bge-small-en-v1.5
    normalize: true

primary_agent:
  llm: default                     
  llm_temperature: 0.0

swiss_airline_policy_rag:
  unstructured_docs: data/unstructured_docs/swiss_airline_policy
  vectordb: data/airline_policy_vectordb
  collection_name: rag-chroma
  llm: default
  llm_temperature: 0.0
  embedding: default              
  chunk_size: 800                 
  chunk_overlap: 120
  k: 4

stories_rag:
  unstructured_docs: data/unstructured_docs/stories
  vectordb: data/stories_vectordb
  collection_name: stories-rag-chroma
  llm: default
  llm_temperature: 0.0
  embedding: default
  chunk_size: 800
  chunk_overlap: 120
  k: 4

travel_sqlagent_configs:
  travel_sqldb_dir: data/travel.sqlite
  llm: default
  llm_temperature: 0.0

chinook_sqlagent_configs:
  chinook_sqldb_dir: data/Chinook.db
  llm: default
  llm_temperature: 0.0

langsmith:
  tracing: true
  project_name: rag_sqlagent_project

keys_env:
  groq: GROQ_API_KEY
  tavily: TAVILY_API_KEY

tavily_search_api:
  tavily_search_max_results: 5

graph_configs:
  thread_id: "dev-thread-01"
